### ISSUE TITLE
Bug: Single clicks are stopped

### ISSUE THREAD

**Issue by btxtiger** [georgipeltekov/ngx-file-drop#200]
I would like to use a fullscreen drop overlay.
Therefor I created a dropzone and added style. However it is not possible anymore to click underlaying elements. `$event.stopPropagation` should not be used for click events.

```html
<ngx-file-drop class="full-drop" [useDragEnter]="true"
                  (onFileDrop)="dropped($event)"
                  (onFileOver)="fileOver($event)" (onFileLeave)="fileLeave($event)">
   <ng-template ngx-file-drop-content-tmp let-openFileSelector="openFileSelector">
   </ng-template>
</ngx-file-drop>
```

```scss
::ng-deep .full-drop {
   .ngx-file-drop__drop-zone {
      position: fixed !important;
      top: 0 !important;
      left: 0 !important;
      width: 100vw !important;
      height: 100vh !important;
      z-index: 999;
      opacity: 0.5;

      &--over {
         opacity: 1;
      }
   }
}
```
