### ISSUE TITLE
How can I modify the drop zone class when hovered?

### ISSUE THREAD

**Issue by antal-horvath** [georgipeltekov/ngx-file-drop#254]
I started to modify the class `.ngx-file-drop__drop-zone--over` in styles.css to achieve this.
But I use ngx-file-drop at different locations where the hovered style should be customized.
As far as I understood, the two arguments `dropZoneClassName` and `contentClassName` do not allow manipulating the hovering effect.

**Comment by akcoder** [comment]
Its entirely possible. Here's an example using RxJS:

```html
<ng-container *ngIf="vm$ | async as vm">
            <ngx-file-drop fxFlex="45%" dropZoneLabel=""
                           (onFileDrop)="vm.dropped($event)" (onFileOver)="vm.fileOver($event)" (onFileLeave)="vm.fileLeave()"
                           [multiple]="false" [showBrowseBtn]="false"
                           accept=".csv,.xls,.xlsx" [directory]="false"
                           contentClassName="" [dropZoneClassName]="vm.dropZoneClassName">
                <ng-template ngx-file-drop-content-tmp>
                        Drop file to upload
                </ng-template>
            </ngx-file-drop>
        </ng-container>
```
```javascript
const AllowedMimeTypes = [
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-excel',
    'text/csv'
];

class FooComponent {
    protected file$ = new BehaviorSubject<File>(null);

    vm$ = combineLatest([this.dropZoneClassName$]).pipe(
        map(([dropZoneClassName]) => {

            return {
                dropZoneClassName,
                dropped: (e: NgxFileDropEntry[]) => this.fileDropped(e),
                fileOver: (e: DragEvent) => this.fileOver(e),
                fileLeave: () => this.dropZoneClassName$.next('dropzone'),
            };
        }),
        shareReplay()
    );

    private fileOver(event: DragEvent): void {
        for (let i = 0; i < event.dataTransfer.items.length; i++) {
            if (!AllowedMimeTypes.includes(event.dataTransfer.items[i].type)) {
                this.dropZoneClassName$.next('dropzone dropzone-denied');
                return;
            }
        }

        this.dropZoneClassName$.next('dropzone dropzone-allowed');
    }

    private fileDropped(files: NgxFileDropEntry[]): void {
        // Reset the dropzone class
        this.dropZoneClassName$.next('dropzone');
    }
}
```
```css
.dropzone {
  border: 2px dashed #bbb;
  border-radius: 5px;
  text-align: center;
  color: #bbb;
  margin: auto;
  padding: 4px;
  white-space: nowrap;
  max-height: 4rem;
}
  .dropzone-denied {
    border: 2px dashed red;
  }

  .dropzone-allowed {
    border: 2px dashed green;
  }

```
